project_id = "upbwlnpycrbhxahjztrf"

[functions.send-contact-email]
verify_jwt = false

[functions.stream-metadata]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.newsletter-campaign]
verify_jwt = true

[functions.newsletter-unsubscribe]
verify_jwt = false

[functions.apple-music-search]
verify_jwt = false

[functions.track-history-updater]
verify_jwt = false

[functions.album-art-search]
verify_jwt = false

[functions.rss-feed-fetch]
verify_jwt = false

[functions.og-meta-generator]
verify_jwt = false

[functions.edm-news-fetcher]
verify_jwt = false

[functions.track-visit]
verify_jwt = false

[functions.subscribe-push]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-test-notification]
verify_jwt = false

[functions.process-scheduled-notifications]
verify_jwt = false

[functions.create-merch-checkout]
verify_jwt = false