/**
 * Episode 400 - Future Dance Anthems with Mario
 * 
 * @generated by scripts/generate-episode.ts v2.0
 * @date 2026-01-01
 * @source https://feeds.blubrry.com/feeds/biggest_tunes_with_mario_135.xml
 * 
 * DO NOT MANUALLY CREATE EPISODE FILES
 * Use: npm run generate-episode
 */

import { ArrowLeft, Calendar, Clock, Music, Play, Pause, Apple } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import SocialShare from '@/components/SocialShare';
import SEO from '@/components/SEO';
import GoogleAds from '@/components/GoogleAds';
import { AD_SLOTS } from '@/config/adSlots';
import TrackAffiliateLinks from '@/components/TrackAffiliateLinks';
import { LoginPrompt } from '@/components/LoginPrompt';
import { EpisodeEqVisualizer } from '@/components/EpisodeEqVisualizer';
import { Link } from 'react-router-dom';
import { useState, useEffect } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { useEpisodePlayer } from '@/hooks/useEpisodePlayer';

interface Track {
  position: number;
  title: string;
  artist: string;
  isUnreleased?: boolean;
}

const Episode400 = () => {
  const episodeNumber = 400;
  const episodeTitle = "Future Dance Anthems with Mario 400";
  const audioUrl = "https://media.blubrry.com/biggest_tunes_with_mario_135/mc.blubrry.com/biggest_tunes_with_mario_135/Biggest-Tunes-with-Mario-400-streamed.mp3?awCollectionId=673838&awEpisodeId=11906368&aw_0_azn.pgenre=Music&aw_0_1st.ri=blubrry&aw_0_azn.pcountry=US&aw_0_azn.planguage=en-us&cat_exclude=IAB1-8%2CIAB1-9%2CIAB7-41%2CIAB8-5%2CIAB8-18%2CIAB11-4%2CIAB23%2CIAB24%2CIAB25%2CIAB26&aw_0_cnt.rss=https%3A%2F%2Ffeeds.blubrry.com%2Ffeeds%2Fbiggest_tunes_with_mario_135.xml";

  const { user } = useAuth();
  const episodeDate = "January 1, 2026";
  
  const { 
    isPlaying, 
    isLoading, 
    currentTime, 
    duration, 
    progress, 
    handlePlayPause, 
    handleSeek, 
    formatTime 
  } = useEpisodePlayer({ episodeNumber, episodeTitle, audioUrl });
  
  const [bgLoaded, setBgLoaded] = useState(false);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  useEffect(() => {
    const img = new Image();
    img.onload = () => setBgLoaded(true);
    img.src = '/lovable-uploads/39bbc48a-9525-463e-bca3-5c21e59f1db7.png';
  }, []);

  const onSeekClick = (e: React.MouseEvent<HTMLDivElement>) => {
    const rect = e.currentTarget.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const percentage = x / rect.width;
    handleSeek(percentage * duration);
  };

  // Track listing for Episode 400
  const tracks: Track[] = [
    { position: 1, title: "Love You So Much", artist: "lllyus & Barrientos Feat. Trina Broussard" },
    { position: 2, title: "The Way I Are (Max Dean Extended Remix)", artist: "Timbaland, Keri Hilson & D.O.E" },
    { position: 3, title: "Sweet Love (Vocal House Mix)", artist: "Sir Gladis" },
    { position: 4, title: "AIR (WARATAH Remix)", artist: "Eli & Fur" },
    { position: 5, title: "AIR (Discognition Remix)", artist: "Eli & Fur" },
    { position: 6, title: "What About My Love (Michael Gray Extended Remix)", artist: "Dave & Maurissa" },
    { position: 7, title: "Giving Up Air (Solomun Remix)", artist: "The Temper Trap" },
    { position: 8, title: "I HEART YOU (Saoirse Remix)", artist: "Confidence Man, Eliza Rose" },
    { position: 9, title: "Lost (Rossi. Remix)", artist: "Frank Ocean" },
    { position: 10, title: "I Like It Like That", artist: "Fcukers" },
    { position: 11, title: "Smooth Operator (Deep House Version)", artist: "Sir Gladis" },
    { position: 12, title: "Painkiller", artist: "Dave (US), Jezu (US)" },
    { position: 13, title: "Hypoxia (Namche Bazaar Remix)", artist: "Peewee Ferris" },
    { position: 14, title: "Hypoxia", artist: "Peewee Ferris" },
    { position: 15, title: "Como Se Llama (Extended Mix)", artist: "Tony Romera" },
    { position: 16, title: "Down by The Beach (Sunset Deep House Remix 2026)", artist: "ReJohn & Sir Gladis" },
    { position: 17, title: "Release (Extended Mix)", artist: "CASSIMM Feat. Tamika Tyan" },
    { position: 18, title: "Lonely No More", artist: "DJ Dove" },
    { position: 19, title: "Rush (Extended Mix)", artist: "Martin Ikin & Hayley May" },
    { position: 20, title: "Digital Loving Arms (Fred again.. Edit)", artist: "Fred again.. x Daft Punk" },
    { position: 21, title: "We Three Kings (Tourist Extended Remix)", artist: "Ella Fitzgerald" },
  ];

  return (
    <div className="min-h-screen bg-background overflow-x-hidden relative">
      <SEO 
        title={`Anthems of the Week ${episodeNumber} | Dance One Radio`}
        description={`Episode ${episodeNumber} featuring the latest electronic dance music anthems.`}
        image="/lovable-uploads/mario-show.jpg"
        url={window.location.href}
      />
      <div 
        className={`fixed inset-0 z-0 opacity-20 transition-opacity duration-500 ${
          bgLoaded ? 'opacity-20' : 'opacity-0'
        }`}
        style={{
          backgroundImage: 'url(/lovable-uploads/39bbc48a-9525-463e-bca3-5c21e59f1db7.png)',
          backgroundSize: 'cover',
          backgroundPosition: 'top center',
          backgroundRepeat: 'no-repeat',
          willChange: 'transform',
          transform: 'translateZ(0)',
          backfaceVisibility: 'hidden'
        }}
      />
      
      <div className="relative z-10">
        <Navigation />
      
      <main className="pt-16">
        <section className="py-12 relative">
          <div className="container mx-auto px-4">
            <div className="mb-8">
              <Link to="/shows">
                <Button variant="ghost" className="mb-4 hover:text-primary">
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Back to Shows
                </Button>
              </Link>
            </div>
            
            <div className="max-w-4xl mx-auto">
              <div className="flex justify-center mb-8">
                <img
                  src="/lovable-uploads/future-dance-anthems.jpg"
                  alt="Future Dance Anthems with Mario - Episode 400"
                  className="w-64 h-64 sm:w-80 sm:h-80 rounded-2xl object-cover shadow-[0_0_30px_hsl(var(--primary)/0.2)]"
                  loading="eager"
                  width="320"
                  height="320"
                  decoding="async"
                  srcSet="/lovable-uploads/future-dance-anthems-480w.jpg 480w, /lovable-uploads/future-dance-anthems-960w.jpg 960w, /lovable-uploads/future-dance-anthems.jpg 1200w"
                  sizes="(max-width: 640px) 100vw, 320px"
                />
              </div>
              <h1 className="text-3xl md:text-5xl font-['Orbitron'] font-bold mb-6 text-center">
                <span className="text-neon">Anthems of the week</span>{" "}
                <span className="text-neon-purple">{episodeNumber}</span>
              </h1>
              
               <Card className="card-cyber p-3 sm:p-6 mb-8">
                <div className="flex flex-wrap items-center justify-center gap-3 sm:gap-6 text-muted-foreground text-sm sm:text-base">
                  <div className="flex items-center gap-2">
                    <Calendar className="w-5 h-5 text-neon" />
                    <span>{episodeDate}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Clock className="w-5 h-5 text-neon-purple" />
                    <span>{duration > 0 ? formatTime(duration) : '1h 2m'}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Music className="w-5 h-5 text-primary" />
                    <span className="px-3 py-1 bg-primary/10 text-primary rounded-full text-sm font-medium">
                      EDM • House • Dance
                    </span>
                  </div>
                </div>
                
                <div className="mt-6 text-center">
                  <p className="text-muted-foreground mb-4 leading-relaxed">
                    Meet Mario at Dance One Radio Mario was discovered through a Dance One Radio search for a newly created 
                    show. He went on to land a brand new show called 'Biggest Tunes with Mario on D1R'. In his own words, Mario 
                    describes his style as "Big Room Sexy house", but because of his love for electronic m...
                  </p>
                  
                  <div className="w-full max-w-2xl mx-auto">
                    <div className="card-cyber p-3 sm:p-6 bg-gradient-to-br from-background/80 to-background/60 backdrop-blur-sm">
                      <div className="flex items-center gap-2 sm:gap-4 mb-4">
                        <Button 
                          variant="ghost"
                          className="w-12 h-12 bg-gradient-to-br from-neon/20 to-neon-purple/20 border border-neon/30 rounded-full flex items-center justify-center hover:from-neon/30 hover:to-neon-purple/30 transition-all duration-200 p-0"
                          onClick={handlePlayPause}
                          disabled={isLoading}
                          aria-label={isPlaying ? 'Pause episode' : 'Play episode'}
                        >
                          {isLoading ? (
                            <div className="w-4 h-4 border-2 border-neon border-t-transparent rounded-full animate-spin" />
                          ) : isPlaying ? (
                            <Pause className="w-6 h-6 text-neon" />
                          ) : (
                            <Play className="w-6 h-6 text-neon" />
                          )}
                        </Button>
                        <div className="flex-1">
                          <h3 className="font-semibold text-primary">Future Dance Anthems with Mario</h3>
                          <p className="text-sm text-muted-foreground">Episode {episodeNumber} - Anthems of the week</p>
                        </div>
                      </div>

                      <div className="mb-4">
                        <EpisodeEqVisualizer isActive={isPlaying} />
                      </div>
                      <div className="space-y-2">
                        <div 
                          className="h-2 bg-primary/40 border border-primary/50 rounded-full cursor-pointer group/progress hover:bg-primary/50 transition-colors"
                          onClick={onSeekClick}
                        >
                          <div 
                            className="h-full bg-neon-purple rounded-full transition-all duration-150 relative"
                            style={{ width: `${duration > 0 ? (currentTime / duration) * 100 : 0}%` }}
                          >
                            <div className="absolute right-0 top-1/2 -translate-y-1/2 w-4 h-4 bg-neon-purple rounded-full shadow-lg shadow-neon-purple/50 opacity-0 group-hover/progress:opacity-100 transition-opacity border-2 border-background" />
                          </div>
                        </div>
                        <div className="flex justify-between text-sm text-primary font-medium">
                          <span>{formatTime(currentTime)}</span>
                          <span>{duration > 0 ? formatTime(duration) : '1:02:37'}</span>
                        </div>
                        <div className="text-right">
                          <p className="text-xs text-muted-foreground">Duration</p>
                          <p className="text-sm font-medium text-neon-purple">{duration > 0 ? formatTime(duration) : '1:02:37'}</p>
                        </div>
                      </div>
                      
                      {!user && (
                        <div className="mt-6">
                          <LoginPrompt />
                        </div>
                      )}
                      
                      {user && progress && progress.playback_position > 30 && (
                        <div className="mt-4 p-3 bg-primary/10 border border-primary/30 rounded-lg">
                          <p className="text-sm text-primary text-center">
                            ✨ Saved progress: Resume from {formatTime(progress.playback_position)}
                          </p>
                        </div>
                      )}
                      
                      <div className="bg-background/50 rounded-lg p-4 border border-neon/20 mt-4">
                        <div className="text-center mb-4">
                          <p className="text-muted-foreground mb-2">
                            This episode is available on our podcast platforms
                          </p>
                          <div className="flex flex-col sm:flex-row justify-center gap-2 sm:gap-4">
                            <Button 
                              asChild 
                              className="bg-gradient-to-r from-neon/20 to-neon-purple/20 border-neon/30 hover:from-neon/30 hover:to-neon-purple/30"
                            >
                              <a 
                                href="https://podcasts.apple.com/us/podcast/future-dance-anthems-with-mario/id1439656478" 
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="flex items-center gap-2"
                              >
                                <Apple className="w-4 h-4" />
                                Listen on Apple Podcasts
                              </a>
                            </Button>
                            <Button 
                              variant="outline" 
                              asChild
                            >
                              <Link to="/player" className="flex items-center gap-2">
                                <Music className="w-4 h-4" />
                                Live Radio
                              </Link>
                            </Button>
                          </div>
                        </div>
                        
                        <div className="text-center">
                          <p className="text-xs text-muted-foreground">
                            Subscribe to get notified when new episodes are available
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  <div className="mt-4">
                    <SocialShare 
                      url={window.location.href}
                      title={`Anthems of the week ${episodeNumber} - Future Dance Anthems with Mario`}
                      description={`Episode ${episodeNumber} featuring the latest electronic dance music anthems.`}
                      image={`${window.location.origin}/lovable-uploads/mario-show.jpg`}
                    />
                  </div>
                </div>
              </Card>
            </div>
          </div>
        </section>

        <GoogleAds key={`episode${episodeNumber}-ad`} slot={AD_SLOTS.IN_CONTENT} />

        {tracks.length > 0 && (
          <section className="py-12">
            <div className="container mx-auto px-4">
              <div className="max-w-4xl mx-auto">
                <h2 className="text-2xl md:text-3xl font-['Orbitron'] font-bold mb-8 text-center">
                  <span className="text-neon-purple">Track Listing</span>
                </h2>
                
                <div className="grid gap-3">
                  {tracks.map((track) => (
                    <Card key={track.position} className="card-cyber p-2 sm:p-4 hover:scale-[1.01] transition-all duration-200 group">
                      <div className="flex items-center gap-2 sm:gap-4">
                        <div className="w-8 h-8 sm:w-12 sm:h-12 bg-gradient-to-br from-neon/20 to-neon-purple/20 border border-neon/30 rounded-full flex items-center justify-center text-neon font-['Orbitron'] font-bold text-xs sm:text-sm shrink-0">
                          {track.position}
                        </div>
                        
                        <div className="flex-1 min-w-0">
                          <h3 className="text-xs sm:text-sm font-semibold text-primary group-hover:text-neon transition-colors break-words sm:truncate">
                            {track.title}
                            {track.isUnreleased && (
                              <span className="ml-2 px-2 py-0.5 bg-neon/20 text-neon text-[10px] sm:text-xs rounded-full">
                                UNRELEASED
                              </span>
                            )}
                          </h3>
                          <p className="text-xs sm:text-sm text-muted-foreground break-words sm:truncate">
                            {track.artist}
                          </p>
                          <div className="sm:hidden">
                            <TrackAffiliateLinks title={track.title} artist={track.artist} variant="mobile" />
                          </div>
                        </div>
                        
                        <div className="hidden sm:block">
                          <TrackAffiliateLinks title={track.title} artist={track.artist} />
                        </div>
                      </div>
                    </Card>
                  ))}
                </div>
              </div>
            </div>
          </section>
        )}
        <GoogleAds key={`episode${episodeNumber}-tracklist-ad`} slot={AD_SLOTS.AFTER_TRACKLIST} format="rectangle" />
      </main>

      <Footer />
      </div>
    </div>
  );
};

export default Episode400;
