/**
 * Episode 403 - Future Dance Anthems with Mario
 * 
 * @generated by scripts/generate-episode.ts v2.0
 * @date 2026-02-07
 * @source https://feeds.blubrry.com/feeds/biggest_tunes_with_mario_135.xml
 * 
 * DO NOT MANUALLY CREATE EPISODE FILES
 * Use: npm run generate-episode
 * 
 * ⚠️ NOTE: Audio URL is a placeholder — update from RSS feed once episode is published.
 */

import { ArrowLeft, Calendar, Clock, Music, Play, Pause, Apple } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import SocialShare from '@/components/SocialShare';
import SEO from '@/components/SEO';
import GoogleAds from '@/components/GoogleAds';
import { LoginPrompt } from '@/components/LoginPrompt';
import { Link } from 'react-router-dom';
import { useState, useEffect } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { useEpisodePlayer } from '@/hooks/useEpisodePlayer';

interface Track {
  position: number;
  title: string;
  artist: string;
  isUnreleased?: boolean;
}

const Episode403 = () => {
  const { user } = useAuth();
  const episodeNumber = 403;
  const episodeTitle = "Future Dance Anthems with Mario 403";
  // TODO: Update audio URL from RSS feed once episode 403 is published
  // Episode 403 is not yet published on the RSS feed — placeholder URL below will not work
  const audioUrl = "";
  const isEpisodeAvailable = audioUrl.length > 0;
  const episodeDate = "February 7, 2026";
  
  const { 
    isPlaying, 
    isLoading, 
    currentTime, 
    duration, 
    progress, 
    handlePlayPause, 
    handleSeek, 
    formatTime 
  } = useEpisodePlayer({ episodeNumber, episodeTitle, audioUrl });
  
  const [bgLoaded, setBgLoaded] = useState(false);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  useEffect(() => {
    const img = new Image();
    img.onload = () => setBgLoaded(true);
    img.src = '/lovable-uploads/39bbc48a-9525-463e-bca3-5c21e59f1db7.png';
  }, []);

  const onSeekClick = (e: React.MouseEvent<HTMLDivElement>) => {
    const rect = e.currentTarget.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const percentage = x / rect.width;
    handleSeek(percentage * duration);
  };

  // Track listing for Episode 403 — from CSV import
  const tracks: Track[] = [
    { position: 1, title: "Feels Good to Move", artist: "Nala" },
    { position: 2, title: "Feel This Way (Extended Mix) [Baker's Dozen]", artist: "Josh Baker, Silva Bumpa, Paige Cavell" },
    { position: 3, title: "909", artist: "Riordan & Danny P" },
    { position: 4, title: "Out Of My Mind", artist: "Bag Raiders" },
    { position: 5, title: "Fara", artist: "Topic" },
    { position: 6, title: "Percy Veering", artist: "Dusky" },
    { position: 7, title: "Everybody Rising (Extended Mix)", artist: "CHANEY" },
    { position: 8, title: "Ballerz", artist: "Beyond Limits" },
    { position: 9, title: "THINKN [bout u] [Extended Mix]", artist: "Kokiri & SELKER" },
    { position: 10, title: "More To Life", artist: "Franky Rizardo & Carston" },
    { position: 11, title: "Numb (Space Motion Remix)", artist: "Elderbrook" },
    { position: 12, title: "Club Bizarre", artist: "Alok, Faithless, Sam Harper & Alex Christensen" },
    { position: 13, title: "Vision Blurred", artist: "Kaskade x CID x Anabel Englund" },
    { position: 14, title: "True Desire", artist: "George Reid" },
    { position: 15, title: "Give You My Luv", artist: "Shermanology" },
    { position: 16, title: "Still Sincere (feat. PinkPantheress)", artist: "MJ Cole" },
  ];

  return (
    <div className="min-h-screen bg-background overflow-x-hidden relative">
      <SEO 
        title={`Anthems of the week ${episodeNumber} - Future Dance Anthems with Mario | Dance One Radio`}
        description={`Episode ${episodeNumber} featuring the latest electronic dance music anthems. 16 tracks including Nala, Josh Baker, Dusky, CHANEY, Kaskade, and more.`}
        image="/lovable-uploads/mario-show.jpg"
        url={window.location.href}
      />
      <div 
        className={`fixed inset-0 z-0 opacity-20 transition-opacity duration-500 ${
          bgLoaded ? 'opacity-20' : 'opacity-0'
        }`}
        style={{
          backgroundImage: 'url(/lovable-uploads/39bbc48a-9525-463e-bca3-5c21e59f1db7.png)',
          backgroundSize: 'cover',
          backgroundPosition: 'top center',
          backgroundRepeat: 'no-repeat',
          willChange: 'transform',
          transform: 'translateZ(0)',
          backfaceVisibility: 'hidden'
        }}
      />
      
      <div className="relative z-10">
        <Navigation />
      
      <main className="pt-16">
        <section className="py-12 relative">
          <div className="container mx-auto px-4">
            <div className="mb-8">
              <Link to="/shows">
                <Button variant="ghost" className="mb-4 hover:text-primary">
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Back to Shows
                </Button>
              </Link>
            </div>
            
            <div className="max-w-4xl mx-auto">
              <h1 className="text-3xl md:text-5xl font-['Orbitron'] font-bold mb-6 text-center">
                <span className="text-neon">Anthems of the week</span>{" "}
                <span className="text-neon-purple">{episodeNumber}</span>
              </h1>
              
              <Card className="card-cyber p-6 mb-8">
                <div className="flex flex-wrap items-center justify-center gap-6 text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <Calendar className="w-5 h-5 text-neon" />
                    <span>{episodeDate}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Clock className="w-5 h-5 text-neon-purple" />
                    <span>{duration > 0 ? formatTime(duration) : '1h 10m'}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Music className="w-5 h-5 text-primary" />
                    <span className="px-3 py-1 bg-primary/10 text-primary rounded-full text-sm font-medium">
                      EDM • House • Dance
                    </span>
                  </div>
                </div>
                
                <div className="mt-6 text-center">
                  <p className="text-muted-foreground mb-4 leading-relaxed">
                    Your clubbers' guide to the weekend. 16 tracks featuring the hottest new dance anthems from 
                    Nala, Josh Baker, Dusky, CHANEY, Kaskade, Elderbrook, MJ Cole, and more.
                  </p>
                  
                  <div className="w-full max-w-2xl mx-auto">
                    <div className="card-cyber p-6 bg-gradient-to-br from-background/80 to-background/60 backdrop-blur-sm">
                      <div className="flex items-center gap-4 mb-4">
                        <Button 
                          variant="ghost"
                          className="w-12 h-12 bg-gradient-to-br from-neon/20 to-neon-purple/20 border border-neon/30 rounded-full flex items-center justify-center hover:from-neon/30 hover:to-neon-purple/30 transition-all duration-200 p-0"
                          onClick={isEpisodeAvailable ? handlePlayPause : undefined}
                          disabled={!isEpisodeAvailable || isLoading}
                        >
                          {isLoading ? (
                            <div className="w-4 h-4 border-2 border-neon border-t-transparent rounded-full animate-spin" />
                          ) : isPlaying ? (
                            <Pause className="w-6 h-6 text-neon" />
                          ) : (
                            <Play className="w-6 h-6 text-neon" />
                          )}
                        </Button>
                        <div className="flex-1">
                          <h3 className="font-semibold text-primary">Future Dance Anthems with Mario</h3>
                          <p className="text-sm text-muted-foreground">
                            {isEpisodeAvailable 
                              ? `Episode ${episodeNumber} - Anthems of the week`
                              : `Episode ${episodeNumber} - Coming soon to streaming`
                            }
                          </p>
                        </div>
                      </div>

                        <div className="space-y-2">
                          <div 
                            className={`h-2 bg-primary/40 border border-primary/50 rounded-full group/progress transition-colors ${isEpisodeAvailable ? 'cursor-pointer hover:bg-primary/50' : 'opacity-50'}`}
                            onClick={isEpisodeAvailable ? onSeekClick : undefined}
                          >
                            <div 
                              className="h-full bg-neon-purple rounded-full transition-all duration-150 relative"
                              style={{ width: `${duration > 0 ? (currentTime / duration) * 100 : 0}%` }}
                            >
                              {isEpisodeAvailable && (
                                <div className="absolute right-0 top-1/2 -translate-y-1/2 w-4 h-4 bg-neon-purple rounded-full shadow-lg shadow-neon-purple/50 opacity-0 group-hover/progress:opacity-100 transition-opacity border-2 border-background" />
                              )}
                            </div>
                          </div>
                          <div className="flex justify-between text-sm text-primary font-medium">
                            <span>{formatTime(currentTime)}</span>
                            <span>{duration > 0 ? formatTime(duration) : '1:10:27'}</span>
                          </div>
                          <div className="text-right">
                            <p className="text-xs text-muted-foreground">Duration</p>
                            <p className="text-sm font-medium text-neon-purple">{duration > 0 ? formatTime(duration) : '1:10:27'}</p>
                          </div>
                        </div>
                        
                        {!isEpisodeAvailable && (
                          <div className="mt-4 p-3 bg-neon-purple/10 border border-neon-purple/30 rounded-lg">
                            <p className="text-sm text-neon-purple text-center font-medium">
                              🎧 This episode hasn't been published to the podcast feed yet. Check back soon!
                            </p>
                          </div>
                        )}
                      
                      {!user && (
                        <div className="mt-6">
                          <LoginPrompt />
                        </div>
                      )}
                      
                      {user && progress && progress.playback_position > 30 && (
                        <div className="mt-4 p-3 bg-primary/10 border border-primary/30 rounded-lg">
                          <p className="text-sm text-primary text-center">
                            ✨ Saved progress: Resume from {formatTime(progress.playback_position)}
                          </p>
                        </div>
                      )}
                      
                      <div className="bg-background/50 rounded-lg p-4 border border-neon/20 mt-4">
                        <div className="text-center mb-4">
                          <p className="text-muted-foreground mb-2">
                            This episode is available on our podcast platforms
                          </p>
                          <div className="flex justify-center gap-4">
                            <Button 
                              asChild 
                              className="bg-gradient-to-r from-neon/20 to-neon-purple/20 border-neon/30 hover:from-neon/30 hover:to-neon-purple/30"
                            >
                              <a 
                                href="https://podcasts.apple.com/us/podcast/future-dance-anthems-with-mario/id1439656478" 
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="flex items-center gap-2"
                              >
                                <Apple className="w-4 h-4" />
                                Listen on Apple Podcasts
                              </a>
                            </Button>
                            <Button 
                              variant="outline" 
                              asChild
                            >
                              <Link to="/player" className="flex items-center gap-2">
                                <Music className="w-4 h-4" />
                                Live Radio
                              </Link>
                            </Button>
                          </div>
                        </div>
                        
                        <div className="text-center">
                          <p className="text-xs text-muted-foreground">
                            Subscribe to get notified when new episodes are available
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  <div className="mt-4">
                    <SocialShare 
                      url={window.location.href}
                      title={`Anthems of the week ${episodeNumber} - Future Dance Anthems with Mario`}
                      description={`Episode ${episodeNumber} featuring the latest electronic dance music anthems.`}
                      image={`${window.location.origin}/lovable-uploads/mario-show.jpg`}
                    />
                  </div>
                </div>
              </Card>
            </div>
          </div>
        </section>

        <GoogleAds key={`episode${episodeNumber}-ad`} slot="6777392184" />

        {tracks.length > 0 && (
          <section className="py-12">
            <div className="container mx-auto px-4">
              <div className="max-w-4xl mx-auto">
                <h2 className="text-2xl md:text-3xl font-['Orbitron'] font-bold mb-8 text-center">
                  <span className="text-neon-purple">Track Listing</span>
                </h2>
                
                <div className="grid gap-3">
                  {tracks.map((track) => (
                    <Card key={track.position} className="card-cyber p-4 hover:scale-[1.01] transition-all duration-200 group">
                      <div className="flex items-center gap-4">
                        <div className="w-12 h-12 bg-gradient-to-br from-neon/20 to-neon-purple/20 border border-neon/30 rounded-full flex items-center justify-center text-neon font-['Orbitron'] font-bold text-sm">
                          {track.position}
                        </div>
                        
                        <div className="flex-1 min-w-0">
                          <h3 className="font-semibold text-primary group-hover:text-neon transition-colors truncate">
                            {track.title}
                            {track.isUnreleased && (
                              <span className="ml-2 px-2 py-1 bg-neon/20 text-neon text-xs rounded-full">
                                UNRELEASED
                              </span>
                            )}
                          </h3>
                          <p className="text-sm text-muted-foreground truncate">
                            {track.artist}
                          </p>
                        </div>
                        
                        <div className="w-8 h-8 flex items-center justify-center text-muted-foreground group-hover:text-neon-purple transition-colors">
                          <Music className="w-4 h-4" />
                        </div>
                      </div>
                    </Card>
                  ))}
                </div>
              </div>
            </div>
          </section>
        )}
      </main>

      <Footer />
      </div>
    </div>
  );
};

export default Episode403;