#!/usr/bin/env tsx
import * as fs from 'fs';
import * as path from 'path';

interface Episode {
  number: number;
  title: string;
  date: string;
  duration: string;
  audioUrl: string;
  description: string;
}

const RSS_FEED_URL = 'https://feeds.blubrry.com/feeds/biggest_tunes_with_mario_135.xml';
const SCRIPT_VERSION = '2.0.0';

// Expected query parameters that indicate a complete audio URL
const REQUIRED_URL_PARAMS = ['awCollectionId', 'awEpisodeId'];

/**
 * Validates that the audio URL contains expected tracking parameters.
 * Returns true if valid, false if potentially incomplete.
 */
function validateAudioUrl(url: string): { valid: boolean; warnings: string[] } {
  const warnings: string[] = [];
  
  for (const param of REQUIRED_URL_PARAMS) {
    if (!url.includes(`${param}=`)) {
      warnings.push(`Missing expected parameter: ${param}`);
    }
  }
  
  // Check URL length - complete URLs are typically > 200 chars
  if (url.length < 150) {
    warnings.push(`URL seems short (${url.length} chars) - may be incomplete`);
  }
  
  return {
    valid: warnings.length === 0,
    warnings
  };
}

/**
 * Generates the file header comment for auto-generated episode files.
 */
function generateFileHeader(episode: Episode): string {
  const timestamp = new Date().toISOString();
  return `/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT MANUALLY CREATE EPISODE FILES
 * 
 * Generated by: scripts/generate-episode.ts v${SCRIPT_VERSION}
 * Generated at: ${timestamp}
 * Source RSS: ${RSS_FEED_URL}
 * Episode: ${episode.number} - ${episode.title}
 * 
 * To create new episodes, run: npm run generate-episode
 * See EPISODE-AUTOMATION.md for documentation.
 * 
 * Manual creation can lead to issues like:
 * - Incomplete audio URLs (missing tracking parameters)
 * - Missing SEO metadata
 * - Inconsistent formatting
 * - Broken routing configuration
 */

`;
}

async function fetchRSSFeed(): Promise<string> {
  console.log('Fetching RSS feed...');
  const response = await fetch(RSS_FEED_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch RSS feed: ${response.statusText}`);
  }
  return await response.text();
}

function parseEpisodeFromRSS(rssContent: string): Episode | null {
  // Extract the most recent episode from RSS feed
  const episodeMatch = rssContent.match(/<item>([\s\S]*?)<\/item>/);
  if (!episodeMatch) return null;

  const item = episodeMatch[1];
  
  // Extract episode number from title (supports both CDATA-wrapped and plain titles)
  const titleMatch = item.match(/<title>(?:<!\[CDATA\[([\s\S]*?)\]\]>|([\s\S]*?))<\/title>/);
  const title = (titleMatch ? (titleMatch[1] ?? titleMatch[2]) : '').trim();
  const numberMatch = title.match(/(\d+)/);
  const episodeNumber = numberMatch ? parseInt(numberMatch[1]) : 0;

  // Extract description (supports CDATA or plain)
  const descMatch = item.match(/<description>(?:<!\[CDATA\[([\s\S]*?)\]\]>|([\s\S]*?))<\/description>/);
  const descriptionRaw = descMatch ? (descMatch[1] ?? descMatch[2] ?? '') : '';
  const description = descriptionRaw.replace(/<[^>]*>/g, '').replace(/&amp;/g, '&').replace(/&quot;/g, '"').trim();

  // Extract audio URL
  const audioMatch = item.match(/<enclosure url="([^"]+)"/);
  const audioUrl = audioMatch ? audioMatch[1] : '';

  // Extract duration
  const durationMatch = item.match(/<itunes:duration>(\d+)<\/itunes:duration>/);
  const durationSeconds = durationMatch ? parseInt(durationMatch[1]) : 0;
  const hours = Math.floor(durationSeconds / 3600);
  const minutes = Math.floor((durationSeconds % 3600) / 60);
  const duration = hours > 0 ? `${hours}h ${minutes}m` : `${minutes}m`;

  // Extract publish date
  const dateMatch = item.match(/<pubDate>(.*?)<\/pubDate>/);
  const pubDate = dateMatch ? new Date(dateMatch[1]) : new Date();
  const date = pubDate.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

  return {
    number: episodeNumber,
    title,
    date,
    duration,
    audioUrl,
    description
  };
}

function episodeExists(episodeNumber: number): boolean {
  const filePath = path.join(process.cwd(), 'src', 'pages', `Episode${episodeNumber}.tsx`);
  return fs.existsSync(filePath);
}

function generateEpisodeFile(episode: Episode): string {
  const header = generateFileHeader(episode);
  return `${header}import { ArrowLeft, Calendar, Clock, Play, Pause, Apple } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import SocialShare from '@/components/SocialShare';
import SEO from '@/components/SEO';
import GoogleAds from '@/components/GoogleAds';
import { LoginPrompt } from '@/components/LoginPrompt';
import { Link } from 'react-router-dom';
import { useState, useEffect, useRef } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { useListeningProgress } from '@/hooks/useListeningProgress';

interface Track {
  position: number;
  title: string;
  artist: string;
  isUnreleased?: boolean;
}

const Episode${episode.number} = () => {
  const { user } = useAuth();
  const episodeNumber = ${episode.number};
  const episodeTitle = "${episode.title}";
  const audioUrl = "${episode.audioUrl}";
  
  const { progress, saveProgress } = useListeningProgress(episodeNumber, episodeTitle, audioUrl);
  
  const [bgLoaded, setBgLoaded] = useState(false);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const audioRef = useRef<HTMLAudioElement>(null);

  // Scroll to top when component mounts
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  // Preload background image for better performance
  useEffect(() => {
    const img = new Image();
    img.onload = () => setBgLoaded(true);
    img.src = '/lovable-uploads/39bbc48a-9525-463e-bca3-5c21e59f1db7.png';
  }, []);

  // Restore progress on load
  useEffect(() => {
    if (progress && audioRef.current && !isPlaying) {
      audioRef.current.currentTime = progress.playback_position;
      setCurrentTime(progress.playback_position);
    }
  }, [progress, isPlaying]);

  // Auto-save progress every 5 seconds when playing
  useEffect(() => {
    if (!user || !isPlaying) return;
    
    const interval = setInterval(() => {
      if (audioRef.current) {
        saveProgress(audioRef.current.currentTime, audioRef.current.duration);
      }
    }, 5000);
    
    return () => clearInterval(interval);
  }, [isPlaying, user, saveProgress]);

  const handlePlayPause = async () => {
    if (!audioRef.current) return;
    
    try {
      setIsLoading(true);
      
      if (isPlaying) {
        audioRef.current.pause();
        setIsPlaying(false);
        
        // Save progress if user is logged in
        if (user) {
          await saveProgress(audioRef.current.currentTime, audioRef.current.duration);
        }
      } else {
        await audioRef.current.play();
        setIsPlaying(true);
      }
    } catch (error) {
      console.error('Error playing audio:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleTimeUpdate = () => {
    if (audioRef.current) {
      setCurrentTime(audioRef.current.currentTime);
    }
  };

  const handleLoadedMetadata = () => {
    if (audioRef.current) {
      setDuration(audioRef.current.duration);
    }
  };

  const handleSeek = (e: React.MouseEvent<HTMLDivElement>) => {
    if (!audioRef.current) return;
    
    const progressBar = e.currentTarget;
    const rect = progressBar.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const percentage = x / rect.width;
    const newTime = percentage * duration;
    
    audioRef.current.currentTime = newTime;
    setCurrentTime(newTime);
  };

  const formatTime = (timeInSeconds: number) => {
    if (isNaN(timeInSeconds)) return '0:00';
    
    const hours = Math.floor(timeInSeconds / 3600);
    const minutes = Math.floor((timeInSeconds % 3600) / 60);
    const seconds = Math.floor(timeInSeconds % 60);
    
    if (hours > 0) {
      return \`\${hours}:\${minutes.toString().padStart(2, '0')}:\${seconds.toString().padStart(2, '0')}\`;
    }
    return \`\${minutes}:\${seconds.toString().padStart(2, '0')}\`;
  };

  // TODO: Import tracks from CSV after generation
  const tracks: Track[] = [];

  return (
    <div className="min-h-screen bg-background overflow-x-hidden relative">
      <SEO 
        title="Anthems of the week ${episode.number} - Future Dance Anthems with Mario | Dance One Radio"
        description="${episode.description}"
        image="/lovable-uploads/39bbc48a-9525-463e-bca3-5c21e59f1db7.png"
        url={window.location.href}
      />
      {/* Optimized Background Image with lazy loading */}
      <div 
        className={\`fixed inset-0 z-0 opacity-20 transition-opacity duration-500 \${
          bgLoaded ? 'opacity-20' : 'opacity-0'
        }\`}
        style={{
          backgroundImage: 'url(/lovable-uploads/39bbc48a-9525-463e-bca3-5c21e59f1db7.png)',
          backgroundSize: 'cover',
          backgroundPosition: 'top center',
          backgroundRepeat: 'no-repeat',
          willChange: 'transform',
          transform: 'translateZ(0)',
          backfaceVisibility: 'hidden'
        }}
      />
      
      {/* Content overlay */}
      <div className="relative z-10">
        <Navigation />
      
      <main className="pt-16">
        {/* Hero Section */}
        <section className="py-12 relative">
          <div className="container mx-auto px-4">
            {/* Back Navigation */}
            <div className="mb-8">
              <Link to="/shows">
                <Button variant="ghost" className="mb-4 hover:text-primary">
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Back to Shows
                </Button>
              </Link>
            </div>
            
            <div className="max-w-4xl mx-auto">
              <h1 className="text-3xl md:text-5xl font-['Orbitron'] font-bold mb-6 text-center">
                <span className="text-neon">Anthems of the week</span>{" "}
                <span className="text-neon-purple">${episode.number}</span>
              </h1>
              
              <Card className="card-cyber p-6 mb-8">
                <div className="flex flex-wrap items-center justify-center gap-6 text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <Calendar className="w-5 h-5 text-neon" />
                    <span>${episode.date}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Clock className="w-5 h-5 text-neon-purple" />
                    <span>{duration > 0 ? formatTime(duration) : 'Loading...'}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Music className="w-5 h-5 text-primary" />
                    <span className="px-3 py-1 bg-primary/10 text-primary rounded-full text-sm font-medium">
                      EDM • House • Dance
                    </span>
                  </div>
                </div>
                
                <div className="mt-6 text-center">
                  <p className="text-muted-foreground mb-4 leading-relaxed">
                    ${episode.description.substring(0, 250)}...
                  </p>
                  
                  <div className="w-full max-w-2xl mx-auto">
                    <audio 
                      ref={audioRef}
                      preload="metadata"
                      onEnded={() => setIsPlaying(false)}
                      onPause={() => setIsPlaying(false)}
                      onPlay={() => setIsPlaying(true)}
                      onTimeUpdate={handleTimeUpdate}
                      onLoadedMetadata={handleLoadedMetadata}
                    >
                      <source src="${episode.audioUrl}" type="audio/mpeg" />
                      Your browser does not support the audio element.
                    </audio>
                    
                    <div className="card-cyber p-6 bg-gradient-to-br from-background/80 to-background/60 backdrop-blur-sm">
                      <div className="flex items-center gap-4 mb-4">
                        <Button 
                          variant="ghost"
                          className="w-12 h-12 bg-gradient-to-br from-neon/20 to-neon-purple/20 border border-neon/30 rounded-full flex items-center justify-center hover:from-neon/30 hover:to-neon-purple/30 transition-all duration-200 p-0"
                          onClick={handlePlayPause}
                          disabled={isLoading}
                        >
                          {isLoading ? (
                            <div className="w-4 h-4 border-2 border-neon border-t-transparent rounded-full animate-spin" />
                          ) : isPlaying ? (
                            <Pause className="w-6 h-6 text-neon" />
                          ) : (
                            <Play className="w-6 h-6 text-neon" />
                          )}
                        </Button>
                        <div className="flex-1">
                          <h3 className="font-semibold text-primary">Future Dance Anthems with Mario</h3>
                          <p className="text-sm text-muted-foreground">Episode ${episode.number} - Anthems of the week</p>
                        </div>
                      </div>

                      {/* Progress Bar */}
                      <div className="space-y-2">
                        <div 
                          className="h-2 bg-primary/40 border border-primary/50 rounded-full cursor-pointer group/progress hover:bg-primary/50 transition-colors"
                          onClick={handleSeek}
                        >
                          <div 
                            className="h-full bg-neon-purple rounded-full transition-all duration-150 relative"
                            style={{ width: \`\${duration > 0 ? (currentTime / duration) * 100 : 0}%\` }}
                          >
                            <div className="absolute right-0 top-1/2 -translate-y-1/2 w-4 h-4 bg-neon-purple rounded-full shadow-lg shadow-neon-purple/50 opacity-0 group-hover/progress:opacity-100 transition-opacity border-2 border-background" />
                          </div>
                        </div>
                        <div className="flex justify-between text-sm text-primary font-medium">
                          <span>{formatTime(currentTime)}</span>
                          <span>{formatTime(duration)}</span>
                        </div>
                        <div className="text-right">
                          <p className="text-xs text-muted-foreground">Duration</p>
                          <p className="text-sm font-medium text-neon-purple">{formatTime(duration)}</p>
                        </div>
                      </div>
                      
                      {!user && (
                        <div className="mt-6">
                          <LoginPrompt />
                        </div>
                      )}
                      
                      {user && progress && progress.playback_position > 30 && (
                        <div className="mt-4 p-3 bg-primary/10 border border-primary/30 rounded-lg">
                          <p className="text-sm text-primary text-center">
                            ✨ Saved progress: Resume from {formatTime(progress.playback_position)}
                          </p>
                        </div>
                      )}
                      
                      <div className="bg-background/50 rounded-lg p-4 border border-neon/20">
                        <div className="text-center mb-4">
                          <p className="text-muted-foreground mb-2">
                            This episode is available on our podcast platforms
                          </p>
                          <div className="flex justify-center gap-4">
                            <Button 
                              asChild 
                              className="bg-gradient-to-r from-neon/20 to-neon-purple/20 border-neon/30 hover:from-neon/30 hover:to-neon-purple/30"
                            >
                              <a 
                                href="https://podcasts.apple.com/us/podcast/future-dance-anthems-with-mario/id1439656478" 
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="flex items-center gap-2"
                              >
                                <Apple className="w-4 h-4" />
                                Listen on Apple Podcasts
                              </a>
                            </Button>
                            <Button 
                              variant="outline" 
                              asChild
                            >
                              <Link to="/player" className="flex items-center gap-2">
                                <Music className="w-4 h-4" />
                                Live Radio
                              </Link>
                            </Button>
                          </div>
                        </div>
                        
                        <div className="text-center">
                          <p className="text-xs text-muted-foreground">
                            Subscribe to get notified when new episodes are available
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  <div className="mt-4">
                    <SocialShare 
                      url={window.location.href}
                      title="Anthems of the week ${episode.number} - Future Dance Anthems with Mario"
                      description="${episode.description.substring(0, 100)}..."
                      image={\`\${window.location.origin}/lovable-uploads/39bbc48a-9525-463e-bca3-5c21e59f1db7.png\`}
                    />
                  </div>
                </div>
              </Card>
            </div>
          </div>
        </section>

        <GoogleAds key="episode${episode.number}-ad" slot="6777392184" />

        {/* Track Listing */}
        <section className="py-12">
          <div className="container mx-auto px-4">
            <div className="max-w-4xl mx-auto">
              <h2 className="text-2xl md:text-3xl font-['Orbitron'] font-bold mb-8 text-center">
                <span className="text-neon-purple">Track Listing</span>
              </h2>
              
              {tracks.length === 0 ? (
                <Card className="card-cyber p-8 text-center">
                  <p className="text-muted-foreground">
                    Track listing will be added soon. Use the CSV importer in the admin panel to add tracks.
                  </p>
                </Card>
              ) : (
                <div className="grid gap-3">
                  {tracks.map((track) => (
                    <Card key={track.position} className="card-cyber p-4 hover:scale-[1.01] transition-all duration-200 group">
                      <div className="flex items-center gap-4">
                        {/* Track Number */}
                        <div className="w-12 h-12 bg-gradient-to-br from-neon/20 to-neon-purple/20 border border-neon/30 rounded-full flex items-center justify-center text-neon font-['Orbitron'] font-bold text-sm">
                          {track.position}
                        </div>
                        
                        {/* Track Info */}
                        <div className="flex-1 min-w-0">
                          <h3 className="font-semibold text-primary group-hover:text-neon transition-colors truncate">
                            {track.title}
                            {track.isUnreleased && (
                              <span className="ml-2 px-2 py-1 bg-neon/20 text-neon text-xs rounded-full">
                                UNRELEASED
                              </span>
                            )}
                          </h3>
                          <p className="text-sm text-muted-foreground truncate">
                            {track.artist}
                          </p>
                        </div>
                        
                        {/* Music Icon */}
                        <div className="w-8 h-8 flex items-center justify-center text-muted-foreground group-hover:text-neon-purple transition-colors">
                          <Music className="w-4 h-4" />
                        </div>
                      </div>
                    </Card>
                  ))}
                </div>
              )}
            </div>
          </div>
        </section>
      </main>

      <Footer />
      </div>
    </div>
  );
};

export default Episode${episode.number};
`;
}

function updateAppRouting(episodeNumber: number): void {
  const appPath = path.join(process.cwd(), 'src', 'App.tsx');
  let appContent = fs.readFileSync(appPath, 'utf-8');

  // Add import
  const importStatement = `import Episode${episodeNumber} from "./pages/Episode${episodeNumber}";`;
  const lastImportMatch = appContent.match(/import Episode\d+ from "\.\/pages\/Episode\d+";/g);
  
  if (lastImportMatch) {
    const lastImport = lastImportMatch[lastImportMatch.length - 1];
    appContent = appContent.replace(lastImport, `${lastImport}\n${importStatement}`);
  } else {
    // Insert after other page imports
    const indexImport = 'import Index from "./pages/Index";';
    appContent = appContent.replace(indexImport, `${indexImport}\n${importStatement}`);
  }

  // Add route
  const routeStatement = `            <Route path="/episode/${episodeNumber}" element={<Episode${episodeNumber} />} />`;
  const lastRouteMatch = appContent.match(/\s+<Route path="\/episode\/\d+" element={<Episode\d+ \/>} \/>/g);
  
  if (lastRouteMatch) {
    const lastRoute = lastRouteMatch[lastRouteMatch.length - 1];
    appContent = appContent.replace(lastRoute, `${lastRoute}\n${routeStatement}`);
  }

  fs.writeFileSync(appPath, appContent, 'utf-8');
  console.log('✓ Updated App.tsx routing');
}

function updateShowsPageAvailableEpisodes(episodeNumber: number): void {
  const showsPath = path.join(process.cwd(), 'src', 'pages', 'Shows.tsx');
  let showsContent = fs.readFileSync(showsPath, 'utf-8');

  // Find and update the availableEpisodePages array
  const arrayMatch = showsContent.match(/const availableEpisodePages = \[([\d,\s]+)\];/);
  
  if (arrayMatch) {
    const currentNumbers = arrayMatch[1].split(',').map(n => parseInt(n.trim())).filter(n => !isNaN(n));
    if (!currentNumbers.includes(episodeNumber)) {
      currentNumbers.push(episodeNumber);
      currentNumbers.sort((a, b) => a - b);
      const newArray = `const availableEpisodePages = [${currentNumbers.join(', ')}];`;
      showsContent = showsContent.replace(/const availableEpisodePages = \[[\d,\s]+\];/, newArray);
      fs.writeFileSync(showsPath, showsContent, 'utf-8');
      console.log('✓ Updated Shows.tsx availableEpisodePages array');
    }
  } else {
    console.warn('⚠️  Could not find availableEpisodePages array in Shows.tsx');
  }
}

function updatePrerenderConfig(episode: Episode): void {
  const prerenderPath = path.join(process.cwd(), 'scripts', 'generate-prerender.ts');
  let prerenderContent = fs.readFileSync(prerenderPath, 'utf-8');

  // Find the routes array and add new episode
  const newRoute = `  {
    path: '/episode/${episode.number}',
    title: 'Anthems of the week ${episode.number} - Future Dance Anthems with Mario | Dance One Radio',
    description: '${episode.description}',
    image: '/lovable-uploads/mario-show.jpg'
  },`;

  // Find the last episode route
  const lastEpisodeMatch = prerenderContent.match(/\s+{\s+path: '\/episode\/\d+',[\s\S]*?image: '[^']+'\s+},/g);
  
  if (lastEpisodeMatch) {
    const lastEpisode = lastEpisodeMatch[lastEpisodeMatch.length - 1];
    prerenderContent = prerenderContent.replace(lastEpisode, `${lastEpisode}\n${newRoute}`);
  }

  fs.writeFileSync(prerenderPath, prerenderContent, 'utf-8');
  console.log('✓ Updated prerender configuration');
}

async function main() {
  try {
    console.log('🚀 Starting automated episode generation...\n');

    // Fetch and parse RSS feed
    const rssContent = await fetchRSSFeed();
    const episode = parseEpisodeFromRSS(rssContent);

    if (!episode) {
      console.error('❌ Could not parse episode data from RSS feed');
      process.exit(1);
    }

    console.log(`\n📻 Found Episode ${episode.number}: ${episode.title}`);
    console.log(`   Date: ${episode.date}`);
    console.log(`   Duration: ${episode.duration}`);
    console.log(`   Audio: ${episode.audioUrl.substring(0, 80)}...`);

    // Validate audio URL
    const urlValidation = validateAudioUrl(episode.audioUrl);
    if (!urlValidation.valid) {
      console.log('\n⚠️  Audio URL validation warnings:');
      urlValidation.warnings.forEach(w => console.log(`   - ${w}`));
      console.log('   Full URL:', episode.audioUrl);
      console.log('\n   Proceeding with generation, but please verify the audio URL is complete.');
    } else {
      console.log('   ✓ Audio URL validated successfully');
    }

    // Check if episode already exists
    if (episodeExists(episode.number)) {
      console.log(`\n⚠️  Episode ${episode.number} already exists. Skipping generation.`);
      process.exit(0);
    }

    // Generate episode file
    console.log('\n📝 Generating episode file...');
    const episodeContent = generateEpisodeFile(episode);
    const episodePath = path.join(process.cwd(), 'src', 'pages', `Episode${episode.number}.tsx`);
    fs.writeFileSync(episodePath, episodeContent, 'utf-8');
    console.log(`✓ Created ${episodePath}`);

    // Update routing
    console.log('\n🔄 Updating routing configuration...');
    updateAppRouting(episode.number);

    // Update Shows page available episodes
    console.log('\n📝 Updating Shows.tsx available episodes...');
    updateShowsPageAvailableEpisodes(episode.number);

    // Update prerender config
    console.log('\n🔧 Updating prerender configuration...');
    updatePrerenderConfig(episode);

    console.log('\n✅ Episode generation complete!');
    console.log(`\n📋 Next steps:`);
    console.log(`   1. Review the generated file: src/pages/Episode${episode.number}.tsx`);
    console.log(`   2. Import track listing CSV to add tracks`);
    console.log(`   3. Test the episode page at /episode/${episode.number}`);
    console.log(`   4. Commit and deploy the changes\n`);

  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
}

main();
