// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-now-playing.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_now_playing_default = defineTool({
  name: "get_now_playing",
  title: "Get now playing",
  description: "Get the track currently playing on the Dance One Radio live stream (title, artist, and album art when available).",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async () => {
    const url = `${process.env.SUPABASE_URL}/functions/v1/stream-metadata`;
    const res = await fetch(url, {
      headers: {
        apikey: process.env.SUPABASE_PUBLISHABLE_KEY ?? "",
        Authorization: `Bearer ${process.env.SUPABASE_PUBLISHABLE_KEY ?? ""}`
      }
    });
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Failed to fetch now playing (${res.status})` }],
        isError: true
      };
    }
    const data = await res.json();
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/get-recent-tracks.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.54.0";
import { z } from "npm:zod@^3.25.76";
var get_recent_tracks_default = defineTool2({
  name: "get_recent_tracks",
  title: "Get recently played tracks",
  description: "List the most recent tracks played on the Dance One Radio live stream, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Number of tracks to return (default 20, max 50).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    const { data, error } = await supabase.from("radio_track_history").select("title, artist, genre, played_at").order("played_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { tracks: data }
    };
  }
});

// src/lib/mcp/tools/list-episodes.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.54.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_episodes_default = defineTool3({
  name: "list_episodes",
  title: "List podcast episodes",
  description: "List Dance One Radio podcast episodes (episode numbers with track counts), newest first. Each episode has a page at https://danceoneradio.com/episode/<episode_number>.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Number of episodes to return (default 20, max 50).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    const { data, error } = await supabase.from("show_tracks").select("episode_number").order("episode_number", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const counts = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      counts.set(row.episode_number, (counts.get(row.episode_number) ?? 0) + 1);
    }
    const episodes = Array.from(counts.entries()).sort((a, b) => b[0] - a[0]).slice(0, limit ?? 20).map(([episode_number, track_count]) => ({
      episode_number,
      track_count,
      url: `https://danceoneradio.com/episode/${episode_number}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(episodes) }],
      structuredContent: { episodes }
    };
  }
});

// src/lib/mcp/tools/get-episode-tracklist.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.54.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_episode_tracklist_default = defineTool4({
  name: "get_episode_tracklist",
  title: "Get episode tracklist",
  description: "Get the full tracklist for a specific Dance One Radio podcast episode, including artist, title, album, and buy/stream links when available.",
  inputSchema: {
    episode_number: z3.number().int().min(1).describe("Episode number, e.g. 416.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ episode_number }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    const { data, error } = await supabase.from("show_tracks").select(
      "track_order, artist, title, album, duration_seconds, apple_music_url, beatport_url, amazon_url"
    ).eq("episode_number", episode_number).order("track_order", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data || data.length === 0) {
      return {
        content: [{ type: "text", text: `No tracks found for episode ${episode_number}.` }]
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: {
        episode_number,
        url: `https://danceoneradio.com/episode/${episode_number}`,
        tracks: data
      }
    };
  }
});

// src/lib/mcp/tools/search-news.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.54.0";
import { z as z4 } from "npm:zod@^3.25.76";
var search_news_default = defineTool5({
  name: "search_edm_news",
  title: "Search EDM news",
  description: "Search Dance One Radio's aggregated EDM news articles by keyword and/or category. Returns title, summary, source, published date, and article URL.",
  inputSchema: {
    query: z4.string().trim().optional().describe("Optional keyword to match in title or summary."),
    category: z4.enum(["top_stories", "artists_releases", "festivals_events", "industry_culture"]).optional().describe("Optional news category filter."),
    limit: z4.number().int().min(1).max(30).optional().describe("Number of articles (default 10, max 30).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY
    );
    let q = supabase.from("edm_news_articles").select("title, summary, category, source_name, source_url, published_at, slug").order("published_at", { ascending: false }).limit(limit ?? 10);
    if (category) q = q.eq("category", category);
    if (query) q = q.or(`title.ilike.%${query}%,summary.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { articles: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "dance-one-radio-mcp",
  title: "Dance One Radio",
  version: "0.1.0",
  instructions: "Tools for Dance One Radio (24/7 electronic dance music radio and podcast). Use `get_now_playing` for the current live stream track, `get_recent_tracks` for recent stream history, `list_episodes` and `get_episode_tracklist` to explore podcast episodes and their tracklists, and `search_edm_news` for the latest aggregated EDM news.",
  tools: [
    get_now_playing_default,
    get_recent_tracks_default,
    list_episodes_default,
    get_episode_tracklist_default,
    search_news_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
