DELETE FROM public.show_tracks WHERE episode_number IN (419,420);
INSERT INTO public.show_tracks (episode_number, track_order, artist, title) VALUES
(419,1,'Morgan Seatree & Laura Davie','Looking For Love'),
(419,2,'KETTAMA','Comes and Goes (Dom Dolla Remix)'),
(419,3,'KILIMANJARO','Ghetto ft. Kojey Radical & Tiggs Da Author'),
(419,4,'Hot Since 82','Life''s Too Short (Erick T Edit)'),
(419,5,'Hot Since 82','Life''s Too Short'),
(419,6,'Cassius','Feeling For You (Fcukers & Junior Sanchez Remix)'),
(419,7,'Adriatique, Rhys from the Sticks','Coming Home'),
(419,8,'Sebastien Tellier','Amnesia (Notre Dame & Harry Kaze Remix)'),
(419,9,'Chasing Kurt','From The Inside (Reznik Remix)'),
(419,10,'Anton Powers x Selker ft Jem Cooke','You Don''t Love Me (Extended Mix)'),
(419,11,'KLP','2AM'),
(419,12,'fran&co','Kundi'),
(419,13,'Malugi, Paige Cavell','Right Thing'),
(419,14,'Cassian & ARCO','Come To Life'),
(419,15,'RDGO','Mad (Extended Mix)'),
(419,16,'PBR Streetgang','Flame Grilled'),
(419,17,'Kolter','Hey Everybody (Back In The Dance)'),
(419,18,'Emanuel Satie & Maga & Tim Engelhardt','Lifted feat. Stee Downes'),
(419,19,'fran&co','Champagne'),
(419,20,'HILLS','Lift Me Up'),
(419,21,'Night Tales','Paradiso'),
(420,1,'KSHMR, Ampermut, Gobi Desert Collective, TEJA','Mirage'),
(420,2,'Gaskin, Ellia Jaya','Dream Or Fantasy'),
(420,3,'The Martinez Brothers','Impressions ft Stevie Appleton'),
(420,4,'Swedish House Mafia, Lykke Li','Happiness Is So Sad (Extended Mix)'),
(420,5,'Malive, & Carlita','Solar Skin'),
(420,6,'Solomun, Skrillex','Rumpta'),
(420,7,'Rossi. & bbyclose','On Your Mind'),
(420,8,'Cleo Grooves','Catch My Love'),
(420,9,'Mont Rouge, AUGUSTE, MESSINA','Dopamine (feat. Syon)'),
(420,10,'Christopher S & Slin Project','Constellations'),
(420,11,'Cloonee & Prospa','Good Girl'),
(420,12,'Saschko, Ocean Seven','Best Friends'),
(420,13,'Samyuel','Infatuation'),
(420,14,'Andy Lakey','Burning Up'),
(420,15,'Michael Fall','To The Beach (Ibiza Remix)'),
(420,16,'Barry Can''t Swim','Dance Dance Dance!');