INSERT INTO public.show_tracks (episode_number, track_order, artist, title) VALUES
(411, 1, 'ECHO', 'Tell Me'),
(411, 2, 'Marsh', 'Pneuma (Volen Sentir Remix)'),
(411, 3, 'Eli & Fur', 'Where Do We Go From Here (Hugo Cantarra Remix)'),
(411, 4, 'Because of Art', 'Thinkin'' Bout You'),
(411, 5, 'Delon', 'Soul To Soul Feat. Eliezer Murad (Extended Mix)'),
(411, 6, 'Chewna', 'Take Me Further'),
(411, 7, 'John Summit & LAVINIA', 'SHADOWS (Original Mix) [Experts Only / Darkroom]'),
(411, 8, 'ZENØN', 'WE ARE ONE (DEFLEE Remix)'),
(411, 9, 'Chris Luno & CEAUS feat. Keilimei', 'Horizon'),
(411, 10, 'Charlotte Haining, Skepsis', 'Slipping'),
(411, 11, 'Groove Armada', 'Love''s Theme'),
(411, 12, 'Tony Romera', 'Waste My Time'),
(411, 13, 'John Summit, The Chainsmokers, Ilsey', 'ALL THE TIME (Radio Edit) [Experts Only / Darkroom]'),
(411, 14, 'ZHU', 'What I Need'),
(411, 15, 'Pithman', 'Cant Stop (Extended Mix)'),
(411, 16, 'Strath', 'Only You'),
(411, 17, 'John Summit, Absolutely', 'DON''T BELIEVE IT (Original Mix) [Experts Only / Darkroom]'),
(411, 18, 'Moon Boots feat. Black Gatsby', 'Hot Minute (Kareem Ali Remix)'),
(411, 19, 'Kroose', 'UNiVRS (Extended Mix)'),
(411, 20, 'Jamiie', 'Tongue Of Flame'),
(411, 21, 'Ian G x Ruff Loaderz', 'Lost With my Friends (Extended Mix)'),
(411, 22, 'Baauer', 'Better (Extended Mix) [LuckyMe]'),
(411, 23, 'HALIENE', 'Solar Waves'),
(411, 24, 'Baauer', 'Better (Extended Mix)'),
(411, 25, 'Icona Pop & Daya', 'Ritual (Extended Mix)'),
(411, 26, 'Joel Corry', 'Devotion (Sweetest Emotion) (feat. RAHH)'),
(411, 27, 'John Summit, Devault, Julia Church', 'SHADES OF BLUE (Original Mix) [Experts Only / Darkroom]'),
(411, 28, 'John Summit, KILIMANJARO', 'TIME WITH YOU'),
(411, 29, 'John Summit, Feid', 'CHICA 305 (Radio Edit) [Experts Only / Darkroom]');