INSERT INTO public.show_tracks (episode_number, track_order, artist, title) VALUES
(412, 1, 'Agoria, Blasé', 'You''re Not Alone (MoBlack, Simone Santagati Remix)'),
(412, 2, 'Wax Motif', 'Something More (Extended Mix)'),
(412, 3, 'Franky Wah', 'Down For You (feat. Jyll)'),
(412, 4, 'Whitesquare', 'Twin Humanities'),
(412, 5, 'Tommy Veanud', 'Same Man (Extended Mix)'),
(412, 6, 'Brunello', 'Ghost Dance'),
(412, 7, 'Victor Flash, Ary Sya', 'Motion'),
(412, 8, 'East Side Beat', 'Ride Like The Wind (Nick Coles Remix)'),
(412, 9, 'Shimza X Ar:Co X Kasango', 'Fire Fire (Gil Glaze Remix)'),
(412, 10, 'Wax Motif', 'You Forget ft. Maeta (Radio Edit)'),
(412, 11, 'Tastexperience', 'Beach Ball (Extended Club Mix)'),
(412, 12, 'Calvin Harris, Jazzy', 'Satisfy'),
(412, 13, 'Meduza & RANI', 'Silence (Extended Mix)'),
(412, 14, 'Kelly Cappuccio', 'Don''t Come Back (Extended Mix)'),
(412, 15, 'Tastexperience', 'Beach Ball (Club Mix)'),
(412, 16, 'ANOTR & 3DDY', 'Like It'),
(412, 17, 'Dunmore Brothers feat. Ben Westbeech', 'TRUST ME'),
(412, 18, 'Peking Duk, Phantogram', 'Forever (Original Mix)'),
(412, 19, 'M.A.N.D.Y. vs Booka Shade', 'Body Language'),
(412, 20, 'Cinnamon Chasers', 'Memories (Nordfold Remix - Radio Edit)');